//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frm_ShanLiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Coupon
    {
        public int No_ { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> CouponID { get; set; }
        public Nullable<int> CouponStatus { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
    }
}
