//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frm_ShanLiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int OrderID { get; set; }
        public int MealsID { get; set; }
        public string MealsName { get; set; }
        public Nullable<decimal> MealsPrice { get; set; }
    
        public virtual Meals_Menu Meals_Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
