//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frm_ShanLiang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShanLiangEntities : DbContext
    {
        public ShanLiangEntities()
            : base("name=ShanLiangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EatType_Method> EatType_Method { get; set; }
        public virtual DbSet<Identification> Identifications { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Member_Action> Member_Action { get; set; }
        public virtual DbSet<Member_Coupon> Member_Coupon { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<Restaurant_Type> Restaurant_Type { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Store_Evaluate> Store_Evaluate { get; set; }
        public virtual DbSet<Store_Type> Store_Type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Store_Image> Store_Image { get; set; }
    }
}
